#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "TKernel" for configuration "Release"
set_property(TARGET TKernel APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKernel PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKernel.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ws2_32;advapi32;gdi32;user32;kernel32;psapi"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKernel.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKernel )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKernel "${_IMPORT_PREFIX}/Win64/lib/TKernel.lib" "${_IMPORT_PREFIX}/Win64/bin/TKernel.dll" )

# Import target "TKMath" for configuration "Release"
set_property(TARGET TKMath APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKMath PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKMath.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKMath.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKMath )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKMath "${_IMPORT_PREFIX}/Win64/lib/TKMath.lib" "${_IMPORT_PREFIX}/Win64/bin/TKMath.dll" )

# Import target "TKG2d" for configuration "Release"
set_property(TARGET TKG2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKG2d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKG2d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKMath"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKG2d.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKG2d )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKG2d "${_IMPORT_PREFIX}/Win64/lib/TKG2d.lib" "${_IMPORT_PREFIX}/Win64/bin/TKG2d.dll" )

# Import target "TKG3d" for configuration "Release"
set_property(TARGET TKG3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKG3d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKG3d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKMath;TKernel;TKG2d"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKG3d.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKG3d )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKG3d "${_IMPORT_PREFIX}/Win64/lib/TKG3d.lib" "${_IMPORT_PREFIX}/Win64/bin/TKG3d.dll" )

# Import target "TKGeomBase" for configuration "Release"
set_property(TARGET TKGeomBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKGeomBase PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKGeomBase.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKMath;TKG2d;TKG3d"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKGeomBase.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKGeomBase )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKGeomBase "${_IMPORT_PREFIX}/Win64/lib/TKGeomBase.lib" "${_IMPORT_PREFIX}/Win64/bin/TKGeomBase.dll" )

# Import target "TKBRep" for configuration "Release"
set_property(TARGET TKBRep APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBRep PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKBRep.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKMath;TKernel;TKG2d;TKG3d;TKGeomBase"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKBRep.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKBRep )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKBRep "${_IMPORT_PREFIX}/Win64/lib/TKBRep.lib" "${_IMPORT_PREFIX}/Win64/bin/TKBRep.dll" )

# Import target "TKGeomAlgo" for configuration "Release"
set_property(TARGET TKGeomAlgo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKGeomAlgo PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKGeomAlgo.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKMath;TKG3d;TKG2d;TKGeomBase;TKBRep"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKGeomAlgo.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKGeomAlgo )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKGeomAlgo "${_IMPORT_PREFIX}/Win64/lib/TKGeomAlgo.lib" "${_IMPORT_PREFIX}/Win64/bin/TKGeomAlgo.dll" )

# Import target "TKTopAlgo" for configuration "Release"
set_property(TARGET TKTopAlgo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKTopAlgo PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKTopAlgo.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKMath;TKernel;TKG2d;TKG3d;TKGeomBase;TKBRep;TKGeomAlgo"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKTopAlgo.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKTopAlgo )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKTopAlgo "${_IMPORT_PREFIX}/Win64/lib/TKTopAlgo.lib" "${_IMPORT_PREFIX}/Win64/bin/TKTopAlgo.dll" )

# Import target "TKPrim" for configuration "Release"
set_property(TARGET TKPrim APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKPrim PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKPrim.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKernel;TKMath;TKG2d;TKGeomBase;TKG3d;TKTopAlgo"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKPrim.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKPrim )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKPrim "${_IMPORT_PREFIX}/Win64/lib/TKPrim.lib" "${_IMPORT_PREFIX}/Win64/bin/TKPrim.dll" )

# Import target "TKBO" for configuration "Release"
set_property(TARGET TKBO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBO PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKBO.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKTopAlgo;TKMath;TKernel;TKG2d;TKG3d;TKGeomAlgo;TKGeomBase;TKPrim"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKBO.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKBO )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKBO "${_IMPORT_PREFIX}/Win64/lib/TKBO.lib" "${_IMPORT_PREFIX}/Win64/bin/TKBO.dll" )

# Import target "TKHLR" for configuration "Release"
set_property(TARGET TKHLR APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKHLR PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKHLR.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKernel;TKMath;TKGeomBase;TKG2d;TKG3d;TKGeomAlgo;TKTopAlgo"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKHLR.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKHLR )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKHLR "${_IMPORT_PREFIX}/Win64/lib/TKHLR.lib" "${_IMPORT_PREFIX}/Win64/bin/TKHLR.dll" )

# Import target "TKMesh" for configuration "Release"
set_property(TARGET TKMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKMesh PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKMesh.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKMath;TKernel;TKG2d;TKG3d;TKGeomBase;TKTopAlgo;TKGeomAlgo"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKMesh.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKMesh )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKMesh "${_IMPORT_PREFIX}/Win64/lib/TKMesh.lib" "${_IMPORT_PREFIX}/Win64/bin/TKMesh.dll" )

# Import target "TKShHealing" for configuration "Release"
set_property(TARGET TKShHealing APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKShHealing PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKShHealing.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKernel;TKMath;TKG2d;TKTopAlgo;TKG3d;TKGeomBase;TKGeomAlgo;ws2_32"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKShHealing.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKShHealing )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKShHealing "${_IMPORT_PREFIX}/Win64/lib/TKShHealing.lib" "${_IMPORT_PREFIX}/Win64/bin/TKShHealing.dll" )

# Import target "TKXMesh" for configuration "Release"
set_property(TARGET TKXMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXMesh PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKXMesh.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKMath;TKernel;TKG2d;TKMesh"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKXMesh.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXMesh )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXMesh "${_IMPORT_PREFIX}/Win64/lib/TKXMesh.lib" "${_IMPORT_PREFIX}/Win64/bin/TKXMesh.dll" )

# Import target "TKBool" for configuration "Release"
set_property(TARGET TKBool APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBool PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKBool.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKTopAlgo;TKMath;TKernel;TKPrim;TKG2d;TKG3d;TKShHealing;TKGeomBase;TKGeomAlgo;TKBO"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKBool.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKBool )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKBool "${_IMPORT_PREFIX}/Win64/lib/TKBool.lib" "${_IMPORT_PREFIX}/Win64/bin/TKBool.dll" )

# Import target "TKFillet" for configuration "Release"
set_property(TARGET TKFillet APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKFillet PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKFillet.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKernel;TKMath;TKGeomBase;TKGeomAlgo;TKG2d;TKTopAlgo;TKG3d;TKBool;TKShHealing"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKFillet.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKFillet )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKFillet "${_IMPORT_PREFIX}/Win64/lib/TKFillet.lib" "${_IMPORT_PREFIX}/Win64/bin/TKFillet.dll" )

# Import target "TKFeat" for configuration "Release"
set_property(TARGET TKFeat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKFeat PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKFeat.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKTopAlgo;TKGeomAlgo;TKMath;TKernel;TKGeomBase;TKPrim;TKG2d;TKBO;TKG3d;TKBool"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKFeat.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKFeat )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKFeat "${_IMPORT_PREFIX}/Win64/lib/TKFeat.lib" "${_IMPORT_PREFIX}/Win64/bin/TKFeat.dll" )

# Import target "TKOffset" for configuration "Release"
set_property(TARGET TKOffset APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKOffset PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKOffset.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKFillet;TKBRep;TKTopAlgo;TKMath;TKernel;TKGeomBase;TKG2d;TKG3d;TKGeomAlgo;TKShHealing;TKBO;TKPrim;TKBool"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKOffset.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKOffset )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKOffset "${_IMPORT_PREFIX}/Win64/lib/TKOffset.lib" "${_IMPORT_PREFIX}/Win64/bin/TKOffset.dll" )

# Import target "TKService" for configuration "Release"
set_property(TARGET TKService APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKService PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKService.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKMath;TKernel;TKBRep;TKShHealing;TKGeomBase;TKGeomAlgo;TKG2d;TKG3d;TKTopAlgo;C:/projects/oce/cmake-build/bin/Release/freetype.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKService.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKService )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKService "${_IMPORT_PREFIX}/Win64/lib/TKService.lib" "${_IMPORT_PREFIX}/Win64/bin/TKService.dll" )

# Import target "TKV3d" for configuration "Release"
set_property(TARGET TKV3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKV3d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKV3d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKMath;TKernel;TKService;TKShHealing;TKTopAlgo;TKG2d;TKG3d;TKGeomBase;TKMesh;TKGeomAlgo;TKHLR;user32;gdi32;glu32;opengl32;C:/projects/oce/cmake-build/bin/Release/freetype.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKV3d.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKV3d )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKV3d "${_IMPORT_PREFIX}/Win64/lib/TKV3d.lib" "${_IMPORT_PREFIX}/Win64/bin/TKV3d.dll" )

# Import target "TKOpenGl" for configuration "Release"
set_property(TARGET TKOpenGl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKOpenGl PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKOpenGl.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKService;TKV3d;glu32;opengl32;vfw32;C:/projects/oce/cmake-build/bin/Release/freetype.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKOpenGl.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKOpenGl )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKOpenGl "${_IMPORT_PREFIX}/Win64/lib/TKOpenGl.lib" "${_IMPORT_PREFIX}/Win64/bin/TKOpenGl.dll" )

# Import target "TKMeshVS" for configuration "Release"
set_property(TARGET TKMeshVS APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKMeshVS PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKMeshVS.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKV3d;TKMath;TKService;TKernel;TKG3d;TKG2d"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKMeshVS.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKMeshVS )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKMeshVS "${_IMPORT_PREFIX}/Win64/lib/TKMeshVS.lib" "${_IMPORT_PREFIX}/Win64/bin/TKMeshVS.dll" )

# Import target "TKNIS" for configuration "Release"
set_property(TARGET TKNIS APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKNIS PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKNIS.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKV3d;TKMath;TKernel;TKService;TKG2d;TKG3d;TKMesh;TKOpenGl;glu32;opengl32"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKNIS.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKNIS )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKNIS "${_IMPORT_PREFIX}/Win64/lib/TKNIS.lib" "${_IMPORT_PREFIX}/Win64/bin/TKNIS.dll" )

# Import target "TKVoxel" for configuration "Release"
set_property(TARGET TKVoxel APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKVoxel PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKVoxel.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKernel;TKV3d;TKMath;TKService;TKGeomBase;TKG2d;TKTopAlgo;TKG3d;TKMesh;glu32;opengl32"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKVoxel.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKVoxel )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKVoxel "${_IMPORT_PREFIX}/Win64/lib/TKVoxel.lib" "${_IMPORT_PREFIX}/Win64/bin/TKVoxel.dll" )

# Import target "TKCDF" for configuration "Release"
set_property(TARGET TKCDF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKCDF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKCDF.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKCDF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKCDF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKCDF "${_IMPORT_PREFIX}/Win64/lib/TKCDF.lib" "${_IMPORT_PREFIX}/Win64/bin/TKCDF.dll" )

# Import target "PTKernel" for configuration "Release"
set_property(TARGET PTKernel APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(PTKernel PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/PTKernel.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/PTKernel.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS PTKernel )
list(APPEND _IMPORT_CHECK_FILES_FOR_PTKernel "${_IMPORT_PREFIX}/Win64/lib/PTKernel.lib" "${_IMPORT_PREFIX}/Win64/bin/PTKernel.dll" )

# Import target "TKLCAF" for configuration "Release"
set_property(TARGET TKLCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKLCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKLCAF.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKCDF;TKernel"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKLCAF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKLCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKLCAF "${_IMPORT_PREFIX}/Win64/lib/TKLCAF.lib" "${_IMPORT_PREFIX}/Win64/bin/TKLCAF.dll" )

# Import target "FWOSPlugin" for configuration "Release"
set_property(TARGET FWOSPlugin APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(FWOSPlugin PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/FWOSPlugin.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKCDF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/FWOSPlugin.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS FWOSPlugin )
list(APPEND _IMPORT_CHECK_FILES_FOR_FWOSPlugin "${_IMPORT_PREFIX}/Win64/lib/FWOSPlugin.lib" "${_IMPORT_PREFIX}/Win64/bin/FWOSPlugin.dll" )

# Import target "TKPShape" for configuration "Release"
set_property(TARGET TKPShape APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKPShape PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKPShape.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKMath;TKernel;TKG2d;TKG3d;PTKernel;TKBRep"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKPShape.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKPShape )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKPShape "${_IMPORT_PREFIX}/Win64/lib/TKPShape.lib" "${_IMPORT_PREFIX}/Win64/bin/TKPShape.dll" )

# Import target "TKBinL" for configuration "Release"
set_property(TARGET TKBinL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBinL PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKBinL.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKCDF;TKernel;TKLCAF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKBinL.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKBinL )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKBinL "${_IMPORT_PREFIX}/Win64/lib/TKBinL.lib" "${_IMPORT_PREFIX}/Win64/bin/TKBinL.dll" )

# Import target "TKXmlL" for configuration "Release"
set_property(TARGET TKXmlL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXmlL PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKXmlL.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKCDF;TKernel;TKMath;TKLCAF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKXmlL.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXmlL )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXmlL "${_IMPORT_PREFIX}/Win64/lib/TKXmlL.lib" "${_IMPORT_PREFIX}/Win64/bin/TKXmlL.dll" )

# Import target "TKPLCAF" for configuration "Release"
set_property(TARGET TKPLCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKPLCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKPLCAF.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKCDF;PTKernel;TKernel;TKLCAF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKPLCAF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKPLCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKPLCAF "${_IMPORT_PREFIX}/Win64/lib/TKPLCAF.lib" "${_IMPORT_PREFIX}/Win64/bin/TKPLCAF.dll" )

# Import target "TKTObj" for configuration "Release"
set_property(TARGET TKTObj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKTObj PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKTObj.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKCDF;TKernel;TKMath;TKLCAF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKTObj.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKTObj )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKTObj "${_IMPORT_PREFIX}/Win64/lib/TKTObj.lib" "${_IMPORT_PREFIX}/Win64/bin/TKTObj.dll" )

# Import target "TKShapeSchema" for configuration "Release"
set_property(TARGET TKShapeSchema APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKShapeSchema PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKShapeSchema.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKG2d;PTKernel;TKMath;TKCDF;TKPShape"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKShapeSchema.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKShapeSchema )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKShapeSchema "${_IMPORT_PREFIX}/Win64/lib/TKShapeSchema.lib" "${_IMPORT_PREFIX}/Win64/bin/TKShapeSchema.dll" )

# Import target "TKStdLSchema" for configuration "Release"
set_property(TARGET TKStdLSchema APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKStdLSchema PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKStdLSchema.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKCDF;PTKernel;TKernel;TKShapeSchema;TKLCAF;TKPLCAF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKStdLSchema.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKStdLSchema )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKStdLSchema "${_IMPORT_PREFIX}/Win64/lib/TKStdLSchema.lib" "${_IMPORT_PREFIX}/Win64/bin/TKStdLSchema.dll" )

# Import target "TKCAF" for configuration "Release"
set_property(TARGET TKCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKCAF.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKGeomBase;TKBRep;TKTopAlgo;TKMath;TKService;TKG2d;TKG3d;TKCDF;TKLCAF;TKV3d;TKBO"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKCAF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKCAF "${_IMPORT_PREFIX}/Win64/lib/TKCAF.lib" "${_IMPORT_PREFIX}/Win64/bin/TKCAF.dll" )

# Import target "TKBin" for configuration "Release"
set_property(TARGET TKBin APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBin PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKBin.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKMath;TKernel;TKG2d;TKG3d;TKCAF;TKCDF;TKLCAF;TKV3d;TKBinL"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKBin.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKBin )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKBin "${_IMPORT_PREFIX}/Win64/lib/TKBin.lib" "${_IMPORT_PREFIX}/Win64/bin/TKBin.dll" )

# Import target "TKXml" for configuration "Release"
set_property(TARGET TKXml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXml PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKXml.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKCDF;TKernel;TKV3d;TKMath;TKBRep;TKG2d;TKGeomBase;TKG3d;TKLCAF;TKCAF;TKXmlL"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKXml.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXml )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXml "${_IMPORT_PREFIX}/Win64/lib/TKXml.lib" "${_IMPORT_PREFIX}/Win64/bin/TKXml.dll" )

# Import target "TKPCAF" for configuration "Release"
set_property(TARGET TKPCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKPCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKPCAF.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "PTKernel;TKBRep;TKMath;TKernel;TKCDF;TKG2d;TKV3d;TKService;TKG3d;TKPShape;TKCAF;TKLCAF;TKPLCAF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKPCAF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKPCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKPCAF "${_IMPORT_PREFIX}/Win64/lib/TKPCAF.lib" "${_IMPORT_PREFIX}/Win64/bin/TKPCAF.dll" )

# Import target "TKBinTObj" for configuration "Release"
set_property(TARGET TKBinTObj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBinTObj PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKBinTObj.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKCDF;TKernel;TKTObj;TKMath;TKLCAF;TKBinL"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKBinTObj.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKBinTObj )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKBinTObj "${_IMPORT_PREFIX}/Win64/lib/TKBinTObj.lib" "${_IMPORT_PREFIX}/Win64/bin/TKBinTObj.dll" )

# Import target "TKXmlTObj" for configuration "Release"
set_property(TARGET TKXmlTObj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXmlTObj PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKXmlTObj.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKCDF;TKernel;TKTObj;TKMath;TKLCAF;TKXmlL"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKXmlTObj.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXmlTObj )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXmlTObj "${_IMPORT_PREFIX}/Win64/lib/TKXmlTObj.lib" "${_IMPORT_PREFIX}/Win64/bin/TKXmlTObj.dll" )

# Import target "TKStdSchema" for configuration "Release"
set_property(TARGET TKStdSchema APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKStdSchema PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKStdSchema.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKCDF;PTKernel;TKPLCAF;TKernel;TKCAF;TKShapeSchema;TKLCAF;TKStdLSchema;TKG3d;TKPShape;TKMath;TKG2d;TKPCAF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKStdSchema.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKStdSchema )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKStdSchema "${_IMPORT_PREFIX}/Win64/lib/TKStdSchema.lib" "${_IMPORT_PREFIX}/Win64/bin/TKStdSchema.dll" )

# Import target "TKSTL" for configuration "Release"
set_property(TARGET TKSTL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTL PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKSTL.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKMath;TKBRep;TKG2d;TKG3d;TKMesh;TKTopAlgo"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKSTL.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKSTL )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKSTL "${_IMPORT_PREFIX}/Win64/lib/TKSTL.lib" "${_IMPORT_PREFIX}/Win64/bin/TKSTL.dll" )

# Import target "TKXSBase" for configuration "Release"
set_property(TARGET TKXSBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXSBase PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKXSBase.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKernel;TKMath;TKG2d;TKG3d;TKTopAlgo;TKGeomBase;TKShHealing"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKXSBase.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXSBase )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXSBase "${_IMPORT_PREFIX}/Win64/lib/TKXSBase.lib" "${_IMPORT_PREFIX}/Win64/bin/TKXSBase.dll" )

# Import target "TKSTEPBase" for configuration "Release"
set_property(TARGET TKSTEPBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTEPBase PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKSTEPBase.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKXSBase;TKMath"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKSTEPBase.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKSTEPBase )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKSTEPBase "${_IMPORT_PREFIX}/Win64/lib/TKSTEPBase.lib" "${_IMPORT_PREFIX}/Win64/bin/TKSTEPBase.dll" )

# Import target "TKIGES" for configuration "Release"
set_property(TARGET TKIGES APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKIGES PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKIGES.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKernel;TKMath;TKTopAlgo;TKShHealing;TKG2d;TKG3d;TKGeomBase;TKGeomAlgo;TKPrim;TKBool;TKOffset;TKXSBase"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKIGES.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKIGES )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKIGES "${_IMPORT_PREFIX}/Win64/lib/TKIGES.lib" "${_IMPORT_PREFIX}/Win64/bin/TKIGES.dll" )

# Import target "TKSTEPAttr" for configuration "Release"
set_property(TARGET TKSTEPAttr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTEPAttr PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKSTEPAttr.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKXSBase;TKSTEPBase"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKSTEPAttr.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKSTEPAttr )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKSTEPAttr "${_IMPORT_PREFIX}/Win64/lib/TKSTEPAttr.lib" "${_IMPORT_PREFIX}/Win64/bin/TKSTEPAttr.dll" )

# Import target "TKSTEP209" for configuration "Release"
set_property(TARGET TKSTEP209 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTEP209 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKSTEP209.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKXSBase;TKSTEPBase"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKSTEP209.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKSTEP209 )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKSTEP209 "${_IMPORT_PREFIX}/Win64/lib/TKSTEP209.lib" "${_IMPORT_PREFIX}/Win64/bin/TKSTEP209.dll" )

# Import target "TKSTEP" for configuration "Release"
set_property(TARGET TKSTEP APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTEP PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKSTEP.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKSTEPAttr;TKSTEP209;TKSTEPBase;TKBRep;TKMath;TKG2d;TKShHealing;TKTopAlgo;TKG3d;TKGeomBase;TKGeomAlgo;TKXSBase;ws2_32"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKSTEP.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKSTEP )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKSTEP "${_IMPORT_PREFIX}/Win64/lib/TKSTEP.lib" "${_IMPORT_PREFIX}/Win64/bin/TKSTEP.dll" )

# Import target "TKVRML" for configuration "Release"
set_property(TARGET TKVRML APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKVRML PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKVRML.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKTopAlgo;TKMath;TKGeomBase;TKernel;TKPrim;TKG2d;TKG3d;TKMesh;TKHLR;TKService;TKGeomAlgo;TKV3d"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKVRML.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKVRML )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKVRML "${_IMPORT_PREFIX}/Win64/lib/TKVRML.lib" "${_IMPORT_PREFIX}/Win64/bin/TKVRML.dll" )

# Import target "TKXCAF" for configuration "Release"
set_property(TARGET TKXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKXCAF.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKernel;TKMath;TKService;TKG2d;TKTopAlgo;TKV3d;TKCDF;TKLCAF;TKG3d;TKCAF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKXCAF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXCAF "${_IMPORT_PREFIX}/Win64/lib/TKXCAF.lib" "${_IMPORT_PREFIX}/Win64/bin/TKXCAF.dll" )

# Import target "TKXCAFSchema" for configuration "Release"
set_property(TARGET TKXCAFSchema APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXCAFSchema PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKXCAFSchema.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKPLCAF;TKernel;PTKernel;TKMath;TKPShape;TKCDF;TKShapeSchema;TKLCAF;TKPCAF;TKXCAF;TKStdLSchema;TKStdSchema"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKXCAFSchema.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXCAFSchema )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXCAFSchema "${_IMPORT_PREFIX}/Win64/lib/TKXCAFSchema.lib" "${_IMPORT_PREFIX}/Win64/bin/TKXCAFSchema.dll" )

# Import target "TKXmlXCAF" for configuration "Release"
set_property(TARGET TKXmlXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXmlXCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKXmlXCAF.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKXmlL;TKBRep;TKCDF;TKMath;TKernel;TKG2d;TKGeomBase;TKCAF;TKG3d;TKLCAF;TKXCAF;TKXml"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKXmlXCAF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXmlXCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXmlXCAF "${_IMPORT_PREFIX}/Win64/lib/TKXmlXCAF.lib" "${_IMPORT_PREFIX}/Win64/bin/TKXmlXCAF.dll" )

# Import target "TKBinXCAF" for configuration "Release"
set_property(TARGET TKBinXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBinXCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKBinXCAF.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKXCAF;TKMath;TKernel;TKBinL;TKG2d;TKCAF;TKCDF;TKG3d;TKLCAF;TKBin"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKBinXCAF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKBinXCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKBinXCAF "${_IMPORT_PREFIX}/Win64/lib/TKBinXCAF.lib" "${_IMPORT_PREFIX}/Win64/bin/TKBinXCAF.dll" )

# Import target "TKXDEIGES" for configuration "Release"
set_property(TARGET TKXDEIGES APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXDEIGES PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKXDEIGES.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKernel;TKMath;TKXSBase;TKCDF;TKLCAF;TKG2d;TKXCAF;TKIGES"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKXDEIGES.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXDEIGES )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXDEIGES "${_IMPORT_PREFIX}/Win64/lib/TKXDEIGES.lib" "${_IMPORT_PREFIX}/Win64/bin/TKXDEIGES.dll" )

# Import target "TKXDESTEP" for configuration "Release"
set_property(TARGET TKXDESTEP APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXDESTEP PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win64/lib/TKXDESTEP.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKSTEPAttr;TKernel;TKMath;TKXSBase;TKG2d;TKCAF;TKSTEPBase;TKCDF;TKLCAF;TKG3d;TKXCAF;TKSTEP"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win64/bin/TKXDESTEP.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXDESTEP )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXDESTEP "${_IMPORT_PREFIX}/Win64/lib/TKXDESTEP.lib" "${_IMPORT_PREFIX}/Win64/bin/TKXDESTEP.dll" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
